### ISSUE TITLE
[0.8.0] Incorrectly escaped CSON

### ISSUE THREAD

**Issue by clintwood** [zacharytamas/atom-polymer#3]
This is causing an error at startup!
Here: https://github.com/zacharytamas/atom-polymer/blob/master/snippets/paper-elements.cson#L71 and here https://github.com/zacharytamas/atom-polymer/blob/master/snippets/paper-elements.cson#L99

**Comment by zacharytamas** [comment]
Oh you're right! I guess the CSON highlighter in Atom didn't catch this in my refactoring. Will fix pronto. Thanks!

**Comment by clintwood** [comment]
Awesome thanks!
