### ISSUE TITLE
No plans for other elements like neon-elements?

### ISSUE THREAD

**Issue by motss** [zacharytamas/atom-polymer#5]
Hi, is there a plan to include other elements as well such as neon-elements, Google Web Components (especially firebase-element)?

**Comment by zacharytamas** [comment]
Hi @motss! Adding new elements is in the works. I'm talking with the Polymer team about the future of this package in light of their new `polymer-atom` package. An official collaboration between a few of these Polymer packages for Atom may be in the works. I'll update this in a week with the latest.

**Comment by motss** [comment]
@zacharytamas  Great! Looking forward to the new release! :grin:

**Comment by zacharytamas** [comment]
You can follow the discussion [here](https://github.com/PolymerLabs/polymer-atom/issues/5).
