### ISSUE TITLE
Handling of imports when creating re-usable elements gives an error

### ISSUE THREAD

**Issue by johnwhitton** [zacharytamas/atom-polymer#7]
When creating a re-usable element according to [this guide](https://www.polymer-project.org/1.0/docs/start/reusableelements.html) importing elements should use
`<link rel="import" href="../paper-menu-button/paper-menu-button.html">`
However this gives an error when using atom-polymer
_paper-menu-button is undefined. at line 62 col 5_
If the link is defined as below no error is given
`<link rel="import" href="./bower_components/paper-menu-button/paper-menu-button.html">`
This can be reproduced using this repository
https://github.com/MeTaNoV/firebase-element-extended

**Comment by Artanis** [comment]
This is just a snippet library. There is no executable code in this repository, and certainly nothing to generate that warning.

The package that makes this warning this is actually [`polymer-atom`](https://github.com/PolymerLabs/polymer-atom), despite naming the linter `atom-polymer` (in [lib/polymer-atom.js#L16](https://github.com/PolymerLabs/polymer-atom/blob/master/lib/polymer-atom.js#L16)). See PolymerLabs/polymer-atom#5.
